variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'npm install --force'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        PUBLIC_URL="." npm run build
    displayName: 'npm build react app'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'build'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/react-web.zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/react-web.zip'
      ArtifactName: 'react-drop'
      publishLocation: 'Container'

# - script: |
#     npm run dist
#   displayName: 'package electron app'

# - task: CmdLine@2
#   inputs:
#     script: 'mkdir pipelineOutput'
#     workingDirectory: '$(Pipeline.Workspace)'

# - task: CopyFiles@2
#   inputs:
#     SourceFolder: 'dist'
#     Contents: '*Setup*.exe*'
#     TargetFolder: '$(Pipeline.Workspace)/pipelineOutput'

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(Pipeline.Workspace)/pipelineOutput'
#     ArtifactName: 'drop'
#     publishLocation: 'Container'


