pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    PUBLIC_URL="." npm run build
  displayName: 'npm build react app'

- script: |
    npm run dist
  displayName: 'package electron app'

- task: CmdLine@2
  inputs:
    script: 'mkdir pipelineOutput'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'dist'
    Contents: '*Setup*.exe*'
    TargetFolder: 'pipelineOutput'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/pipelineOutput'
    artifact: 'drop'
    publishLocation: 'pipeline'