pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    PUBLIC_URL="." npm run build
  displayName: 'npm build react app'

- script: |
    npm run dist
  displayName: 'package electron app'

- task: CmdLine@2
  inputs:
    script: 'ls'

- task: CmdLine@2
  inputs:
    script: 'ls'
    workingDirectory: 'dist'

- task: CmdLine@2
  inputs:
    script: 'mkdir pipelineOutput'
    workingDirectory: '$(Pipeline.Workspace)'

- task: CopyFiles@2
  inputs:
    Contents: '**Setup*.exe*'
    TargetFolder: '$(Pipeline.Workspace)/pipelineOutput'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Pipeline.Workspace)/pipelineOutput'
    ArtifactName: 'drop'
    publishLocation: 'Container'